_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "6": 4.46.3
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
BATCH_SIZE:
    value: 8
EPOCHS:
    value: 1
GRAD_ACCUM_STEPS:
    value: 2
LR:
    value: 1e-05
